package main.java.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.time.Duration;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import main.java.dws.Schedule;
import main.java.dws.Scheduler;
import main.java.util.Persistence;


public class AddJobView extends JFrame {

  private final Scheduler scheduler;
  private JTextField urlField;
  private JLabel urlLabel;
  private JPanel mainPanel;
  private JButton addJobBtn;
  private JTextField intervalField;
  private JLabel intervalLabel;
  private boolean intervalValid = false;

  public AddJobView(String title, Scheduler scheduler) {
    super(title);
    this.scheduler = scheduler;
    this.setContentPane(mainPanel);
    this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    this.pack();

    urlField.addKeyListener(new KeyListener() {

      @Override
      public void keyTyped(KeyEvent e) {
        // ignored
      }

      @Override
      public void keyPressed(KeyEvent e) {
        // ignored
      }

      @Override
      public void keyReleased(KeyEvent e) {
        if (urlField.getText().isEmpty()) {
          urlField.setBackground(Color.RED);
        } else {
          urlField.setBackground(Color.white);
        }
      }
    });

    intervalField.addKeyListener(new KeyListener() {

      @Override
      public void keyTyped(KeyEvent e) {
        // ignored
      }

      @Override
      public void keyPressed(KeyEvent e) {
        // ignored
      }

      @Override
      public void keyReleased(KeyEvent e) {
        checkIfIntervalValid();
      }
    });

    addJobBtn.addActionListener(e -> {
      checkIfIntervalValid();
      if (urlField.getText().isEmpty()) {
        urlField.setBackground(Color.RED);
      } else {
        if (intervalValid) {
          String durationStrng = "PT" + intervalField.getText();
          Schedule add = new Schedule(urlField.getText(), Duration.parse(durationStrng));
          scheduler.addSchedule(add, true);
          Persistence.save(scheduler);
          this.dispose();
        }
      }
    });
  }

  private void checkIfIntervalValid() {
    boolean isValid = true;
    String durationStrng = "PT" + intervalField.getText();
    try {
      Duration.parse(durationStrng);
    } catch (Exception ignored) {
      isValid = false;
    }
    intervalValid = isValid;
    intervalField.setBackground(intervalValid ? Color.white : Color.RED);
  }

  public void resetView() {
    this.urlField.setText("");
    this.intervalField.setText("");
    this.urlField.setBackground(Color.WHITE);
    this.intervalField.setBackground(Color.WHITE);
  }


  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
    final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
    mainPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    urlLabel = new JLabel();
    urlLabel.setText("URL:");
    mainPanel.add(urlLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    urlField = new JTextField();
    urlField.setText("");
    mainPanel.add(urlField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    intervalField = new JTextField();
    intervalField.setText("");
    mainPanel.add(intervalField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    intervalLabel = new JLabel();
    intervalLabel.setText("Interval:");
    mainPanel.add(intervalLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("Interval Format:  {AMOUNT}{UNIT}");
    mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    addJobBtn = new JButton();
    addJobBtn.setText("Add Job");
    mainPanel.add(addJobBtn, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label2 = new JLabel();
    label2.setText(" i.E. 20S = every 20 seconds");
    mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
