package main.java.ui;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;

import main.java.dws.Schedule;
import main.java.dws.Scheduler;
import main.java.util.Persistence;

public class SchedulesView extends JFrame {

  private final Scheduler scheduler;
  private JButton addJobBtn;
  private JButton settingsBtn;
  private JList jobList;
  private JPanel mainPanel;
  private JButton deleteJobBtn;
  private JButton editJobBtn;
  private DefaultListModel jobModel;


  public SchedulesView(String title, Scheduler scheduler) {
    super(title);
    this.scheduler = scheduler;
    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    this.setContentPane(mainPanel);
    this.pack();
    jobModel = new DefaultListModel();
    jobList.setModel(jobModel);

    addJobBtn.addActionListener(e -> {
      scheduler.getAddJobFrame().resetView();
      scheduler.getAddJobFrame().setVisible(true);
    });

    deleteJobBtn.addActionListener(e -> {
      scheduler.deleteJob(jobList.getSelectedIndex());
    });

    jobList.addMouseListener(new MouseAdapter() {

      public void mouseClicked(MouseEvent evt) {
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
          // Double-click detected
          int index = list.locationToIndex(evt.getPoint());
          Schedule schedule = scheduler.getSchedules().get(index);
          if (schedule.getLastResult() != null) {
            ScheduleResult scheduleResultFrame = new ScheduleResult("Result", schedule);
            scheduleResultFrame.setLocationRelativeTo(null);
            scheduleResultFrame.setResizable(false);
            scheduleResultFrame.setMinimumSize(new Dimension(550, 300));
            scheduleResultFrame.setVisible(true);
          }
        }
      }
    });

    settingsBtn.addActionListener(e -> {
      Persistence.openConfigWithOSHandler();
    });
  }

  public JButton getAddJobBtn() {
    return addJobBtn;
  }

  public JButton getDeleteJobBtn() {
    return settingsBtn;
  }

  public JList getJobList() {
    return jobList;
  }

  // TODO refactor this mess, maybe show last status code?
  public void syncJobs() {
    jobModel.removeAllElements();
    for (Schedule s : scheduler.getSchedules()) {
      String resChar;
      if (s.getLastResult() == null) {
        resChar = "?";
      } else {
        resChar = s.getLastResult().wasSuccess() ? new String(Character.toChars(10003)) : "X";
      }

      jobModel.addElement(resChar + "  - " + s.getUrl());
    }
  }

  public void updateJobs() {
    int i = 0;
    for (Schedule s : scheduler.getSchedules()) {
      String resChar;
      if (s.getLastResult() == null) {
        resChar = "?";
      } else {
        resChar = s.getLastResult().wasSuccess() ? new String(Character.toChars(10003)) : "X";
      }
      jobModel.setElementAt(resChar + "  - " + s.getUrl(), i++);
    }
  }

  public JPanel getMainPanel() {
    return mainPanel;
  }

  public JButton getEditJobBtn() {
    return editJobBtn;
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
    mainPanel.setMinimumSize(new Dimension(300, 150));
    addJobBtn = new JButton();
    addJobBtn.setText("Add new Job");
    mainPanel.add(addJobBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    settingsBtn = new JButton();
    settingsBtn.setText("Settings");
    mainPanel.add(settingsBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    jobList = new JList();
    final DefaultListModel defaultListModel1 = new DefaultListModel();
    jobList.setModel(defaultListModel1);
    mainPanel.add(jobList, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0,
        false));
    deleteJobBtn = new JButton();
    deleteJobBtn.setText("Delete selected Job");
    mainPanel.add(deleteJobBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
